import Constants from '../constants/Constants';
export default {
  all: Constants.primaryDark,
  allAccent: Constants.lightBlue,
  fuel: 'mediumseagreen',
  fuelAccent: 'forestgreen',
  registration: 'blue',
  registrationAccent: 'darkblue',
  registration2: 'indigo',
  registration2Accent: 'darkblue',
  insurance: 'lightblue',
  insuranceAccent: 'blue',
  maintainance: 'orange',
  maintainanceAccent: 'red',
  repair: 'coral',
  repairAccent: 'purple',
  crashes: 'crimson',
  crashesAccent: 'purple',
  equipment: 'mediumturquoise',
  equipmentAccent: 'teal',
  tickets: 'slateblue',
  ticketsAccent: 'dodgerblue',
  carWash: 'white',
  carWashAccent: 'steelblue',
  other: 'sandybrown',
  otherAccent: 'orange',
};
